### PR TITLE
homepage animation

### PR DESCRIPTION
**Pull request by starlightknown**
homepage

This is a moving animation for landing page. @kulendu @bishalr0y  let me know your thoughts

### CODE REVIEW

**Comment by kulendu** [comment]
@starlightknown this looks good. But I was thinking that making it a bit of light coloured  / ligh themed page will look better.

**Comment by starlightknown** [comment]
> @starlightknown this looks good. But I was thinking that making it a bit of light coloured / ligh themed page will look better.

I'm planning two pages where one is the welcome page and the other where users interact with our app, possible?

**Comment by kulendu** [comment]
Ya one page will show while loading the interacting page. And I guess @bishalr0y can do that. I am not that great with server side programing.

**Comment by bishalr0y** [comment]
The page looks great. I think it would look much better if we increase the size of the text and its colour. The text is getting blended in the background.

**Comment by starlightknown** [comment]
I'll add you as collaborators to this repo, you will have push permissions. We can make changes and you don't have to wait until merging.

**Comment by starlightknown** [comment]
> The page looks great. I think it would look much better if we increase the size of the text and change its colour. The text is getting blended in the background.

Agree. Which colour would be better? You can review and suggest changes here so I can do it

**Comment by bishalr0y** [comment]
> > The page looks great. I think it would look much better if we increase the size of the text and change its colour. The text is getting blended in the background.
> 
> Agree. Which colour would be better? You can review and suggest changes here so I can do it

I have to try various colours and check which sticks around. I'll let you know.

**Comment by kulendu** [comment]
I really this one. Can we do something like this 👇
https://www.awwwards.com/inspiration/kayma-stories-loading-animation

**Comment by bishalr0y** [comment]
> I really this one. Can we do something like this 👇
> https://www.awwwards.com/inspiration/kayma-stories-loading-animation

This really looks awesome🚀

**Comment by starlightknown** [comment]
Wow so cool!

**Pull request merged**
